### ISSUE TITLE
Hi Stefano.

### ISSUE THREAD

**Issue by poudigne** [StefanoFiumara/Gunbound-Clone#7]
I tried to implement your code in my own gunbound-like project, and I am getting weird behaviour. I would like if you could take a look, and help me fix it.

You can find my repo on my profile under the name "TankLike"

Thanks

**Comment by StefanoFiumara** [comment]
Hello,

It's been a long time since I've looked at my code for this project (lack of time and motivation), so I'm not sure if I'll be able to help.

Regardless, you're going to have to be more specific with regards to the issues you are having.

If you have further questions, please send me a private message, as issues here should pertain specifically to the code in this repository.
